# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'D:\Apps\DEV\PROJECTS\KoHighlights\gui_main.ui'
#
# Created: Thu Feb  6 12:55:05 2020
#      by: pyside-uic 0.2.15 running on PySide 1.2.4
#
# WARNING! All changes made in this file will be lost!

from boot_config import *

if QT4:  # ___ ______________ DEPENDENCIES __________________________
    from PySide.QtGui import *
    from PySide import QtCore
else:
    from PySide2.QtWidgets import *
    from PySide2.QtGui import *
    from PySide2 import QtCore

class Ui_Base(object):
    def setupUi(self, Base):
        Base.setObjectName("Base")
        Base.resize(624, 412)
        icon = QIcon()
        icon.addPixmap(QPixmap(":/stuff/logo64.png"), QIcon.Normal, QIcon.Off)
        Base.setWindowIcon(icon)
        Base.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedStates))
        Base.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.centralwidget = QWidget(Base)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_2 = QVBoxLayout(self.centralwidget)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.views = QStackedWidget(self.centralwidget)
        self.views.setObjectName("views")
        self.books_pg = QWidget()
        self.books_pg.setObjectName("books_pg")
        self.verticalLayout_3 = QVBoxLayout(self.books_pg)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.splitter = QSplitter(self.books_pg)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.file_table = DropTableWidget(self.splitter)
        self.file_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.file_table.setFrameShape(QFrame.WinPanel)
        self.file_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.file_table.setDragDropMode(QAbstractItemView.DropOnly)
        self.file_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.file_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.file_table.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.file_table.setWordWrap(False)
        self.file_table.setCornerButtonEnabled(False)
        self.file_table.setColumnCount(7)
        self.file_table.setObjectName("file_table")
        self.file_table.setColumnCount(7)
        self.file_table.setRowCount(0)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.file_table.setHorizontalHeaderItem(6, item)
        self.file_table.horizontalHeader().setHighlightSections(False)
        self.file_table.horizontalHeader().setMinimumSectionSize(22)
        self.file_table.horizontalHeader().setSortIndicatorShown(True)
        self.file_table.verticalHeader().setDefaultSectionSize(22)
        self.file_table.verticalHeader().setHighlightSections(True)
        self.file_table.verticalHeader().setMinimumSectionSize(22)
        self.frame = QFrame(self.splitter)
        self.frame.setFrameShape(QFrame.WinPanel)
        self.frame.setFrameShadow(QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.verticalLayout = QVBoxLayout(self.frame)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.header = QWidget(self.frame)
        self.header.setObjectName("header")
        self.horizontalLayout = QHBoxLayout(self.header)
        self.horizontalLayout.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.fold_btn = QToolButton(self.header)
        self.fold_btn.setStyleSheet("QToolButton{border:none;}")
        self.fold_btn.setCheckable(True)
        self.fold_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.fold_btn.setArrowType(QtCore.Qt.DownArrow)
        self.fold_btn.setObjectName("fold_btn")
        self.horizontalLayout.addWidget(self.fold_btn)
        self.frame_2 = QFrame(self.header)
        sizePolicy = QSizePolicy(QSizePolicy.Expanding, QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.frame_2.sizePolicy().hasHeightForWidth())
        self.frame_2.setSizePolicy(sizePolicy)
        self.frame_2.setFrameShape(QFrame.HLine)
        self.frame_2.setFrameShadow(QFrame.Sunken)
        self.frame_2.setLineWidth(1)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout.addWidget(self.frame_2)
        self.verticalLayout.addWidget(self.header)
        self.book_info = QFrame(self.frame)
        self.book_info.setFrameShape(QFrame.StyledPanel)
        self.book_info.setFrameShadow(QFrame.Raised)
        self.book_info.setObjectName("book_info")
        self.gridLayout = QGridLayout(self.book_info)
        self.gridLayout.setContentsMargins(6, 0, 6, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.title_lbl = QLabel(self.book_info)
        self.title_lbl.setObjectName("title_lbl")
        self.gridLayout.addWidget(self.title_lbl, 0, 0, 1, 1)
        self.series_lbl = QLabel(self.book_info)
        self.series_lbl.setObjectName("series_lbl")
        self.gridLayout.addWidget(self.series_lbl, 2, 0, 1, 1)
        self.author_lbl = QLabel(self.book_info)
        self.author_lbl.setObjectName("author_lbl")
        self.gridLayout.addWidget(self.author_lbl, 1, 0, 1, 1)
        self.lang_lbl = QLabel(self.book_info)
        self.lang_lbl.setObjectName("lang_lbl")
        self.gridLayout.addWidget(self.lang_lbl, 4, 0, 1, 1)
        self.pages_lbl = QLabel(self.book_info)
        self.pages_lbl.setObjectName("pages_lbl")
        self.gridLayout.addWidget(self.pages_lbl, 4, 3, 1, 1)
        self.lang_txt = QLineEdit(self.book_info)
        self.lang_txt.setReadOnly(True)
        self.lang_txt.setObjectName("lang_txt")
        self.gridLayout.addWidget(self.lang_txt, 4, 2, 1, 1)
        self.pages_txt = QLineEdit(self.book_info)
        self.pages_txt.setReadOnly(True)
        self.pages_txt.setObjectName("pages_txt")
        self.gridLayout.addWidget(self.pages_txt, 4, 4, 1, 1)
        self.tags_lbl = QLabel(self.book_info)
        self.tags_lbl.setObjectName("tags_lbl")
        self.gridLayout.addWidget(self.tags_lbl, 3, 0, 1, 1)
        self.description_btn = QToolButton(self.book_info)
        icon1 = QIcon()
        icon1.addPixmap(QPixmap(":/stuff/description.png"), QIcon.Normal, QIcon.Off)
        self.description_btn.setIcon(icon1)
        self.description_btn.setToolButtonStyle(QtCore.Qt.ToolButtonTextBesideIcon)
        self.description_btn.setObjectName("description_btn")
        self.gridLayout.addWidget(self.description_btn, 4, 5, 1, 1)
        self.tags_txt = QLineEdit(self.book_info)
        self.tags_txt.setReadOnly(True)
        self.tags_txt.setObjectName("tags_txt")
        self.gridLayout.addWidget(self.tags_txt, 3, 2, 1, 4)
        self.series_txt = QLineEdit(self.book_info)
        self.series_txt.setReadOnly(True)
        self.series_txt.setObjectName("series_txt")
        self.gridLayout.addWidget(self.series_txt, 2, 2, 1, 4)
        self.author_txt = QLineEdit(self.book_info)
        self.author_txt.setReadOnly(True)
        self.author_txt.setObjectName("author_txt")
        self.gridLayout.addWidget(self.author_txt, 1, 2, 1, 4)
        self.title_txt = QLineEdit(self.book_info)
        self.title_txt.setReadOnly(True)
        self.title_txt.setObjectName("title_txt")
        self.gridLayout.addWidget(self.title_txt, 0, 2, 1, 4)
        self.verticalLayout.addWidget(self.book_info)
        self.high_list = QListWidget(self.frame)
        self.high_list.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.high_list.setFrameShape(QFrame.WinPanel)
        self.high_list.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.high_list.setSelectionMode(QAbstractItemView.ExtendedSelection)
        self.high_list.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.high_list.setVerticalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.high_list.setWordWrap(True)
        self.high_list.setObjectName("high_list")
        self.verticalLayout.addWidget(self.high_list)
        self.verticalLayout_3.addWidget(self.splitter)
        self.views.addWidget(self.books_pg)
        self.highlights_pg = QWidget()
        self.highlights_pg.setObjectName("highlights_pg")
        self.verticalLayout_4 = QVBoxLayout(self.highlights_pg)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.high_table = QTableWidget(self.highlights_pg)
        self.high_table.setContextMenuPolicy(QtCore.Qt.CustomContextMenu)
        self.high_table.setFrameShape(QFrame.WinPanel)
        self.high_table.setEditTriggers(QAbstractItemView.NoEditTriggers)
        self.high_table.setDragDropMode(QAbstractItemView.DropOnly)
        self.high_table.setDefaultDropAction(QtCore.Qt.CopyAction)
        self.high_table.setSelectionBehavior(QAbstractItemView.SelectRows)
        self.high_table.setHorizontalScrollMode(QAbstractItemView.ScrollPerPixel)
        self.high_table.setWordWrap(False)
        self.high_table.setCornerButtonEnabled(False)
        self.high_table.setColumnCount(7)
        self.high_table.setObjectName("high_table")
        self.high_table.setColumnCount(7)
        self.high_table.setRowCount(0)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(0, item)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(1, item)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(2, item)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(3, item)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(4, item)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(5, item)
        item = QTableWidgetItem()
        self.high_table.setHorizontalHeaderItem(6, item)
        self.high_table.horizontalHeader().setHighlightSections(False)
        self.high_table.horizontalHeader().setMinimumSectionSize(22)
        self.high_table.horizontalHeader().setSortIndicatorShown(True)
        self.high_table.horizontalHeader().setStretchLastSection(True)
        self.high_table.verticalHeader().setDefaultSectionSize(22)
        self.high_table.verticalHeader().setHighlightSections(True)
        self.high_table.verticalHeader().setMinimumSectionSize(22)
        self.verticalLayout_4.addWidget(self.high_table)
        self.views.addWidget(self.highlights_pg)
        self.verticalLayout_2.addWidget(self.views)
        Base.setCentralWidget(self.centralwidget)
        self.statusbar = QStatusBar(Base)
        self.statusbar.setStyleSheet("QStatusBar{padding-left:8px;font-weight:bold;}")
        self.statusbar.setObjectName("statusbar")
        Base.setStatusBar(self.statusbar)
        self.tool_bar = QToolBar(Base)
        self.tool_bar.setWindowTitle("toolBar")
        self.tool_bar.setMovable(True)
        self.tool_bar.setAllowedAreas(QtCore.Qt.BottomToolBarArea|QtCore.Qt.TopToolBarArea)
        self.tool_bar.setIconSize(QtCore.QSize(32, 32))
        self.tool_bar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.tool_bar.setObjectName("tool_bar")
        Base.addToolBar(QtCore.Qt.TopToolBarArea, self.tool_bar)
        self.act_english = QAction(Base)
        self.act_english.setCheckable(True)
        self.act_english.setChecked(False)
        self.act_english.setObjectName("act_english")
        self.act_greek = QAction(Base)
        self.act_greek.setCheckable(True)
        self.act_greek.setChecked(False)
        self.act_greek.setObjectName("act_greek")
        self.act_view_book = QAction(Base)
        icon2 = QIcon()
        icon2.addPixmap(QPixmap(":/stuff/files_view.png"), QIcon.Normal, QIcon.Off)
        self.act_view_book.setIcon(icon2)
        self.act_view_book.setObjectName("act_view_book")

        self.retranslateUi(Base)
        self.views.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Base)

    def retranslateUi(self, Base):
        self.file_table.setSortingEnabled(True)
        self.file_table.horizontalHeaderItem(0).setText(QApplication.translate("Base", "Title", None))
        self.file_table.horizontalHeaderItem(1).setText(QApplication.translate("Base", "Author", None))
        self.file_table.horizontalHeaderItem(2).setText(QApplication.translate("Base", "Type", None))
        self.file_table.horizontalHeaderItem(3).setText(QApplication.translate("Base", "Percent", None))
        self.file_table.horizontalHeaderItem(4).setText(QApplication.translate("Base", "Rating", None))
        self.file_table.horizontalHeaderItem(5).setText(QApplication.translate("Base", "Modified", None))
        self.file_table.horizontalHeaderItem(6).setText(QApplication.translate("Base", "Path", None))
        self.fold_btn.setText(QApplication.translate("Base", "Hide Book Info", None))
        self.title_lbl.setText(QApplication.translate("Base", "Title", None))
        self.series_lbl.setText(QApplication.translate("Base", "Series", None))
        self.author_lbl.setText(QApplication.translate("Base", "Author", None))
        self.lang_lbl.setText(QApplication.translate("Base", "Language", None))
        self.pages_lbl.setText(QApplication.translate("Base", "Pages", None))
        self.tags_lbl.setText(QApplication.translate("Base", "Tags", None))
        self.description_btn.setText(QApplication.translate("Base", "Description", None))
        self.high_table.setSortingEnabled(True)
        self.high_table.horizontalHeaderItem(0).setText(QApplication.translate("Base", "Highlight", None))
        self.high_table.horizontalHeaderItem(1).setText(QApplication.translate("Base", "Comment", None))
        self.high_table.horizontalHeaderItem(2).setText(QApplication.translate("Base", "Date", None))
        self.high_table.horizontalHeaderItem(3).setText(QApplication.translate("Base", "Title", None))
        self.high_table.horizontalHeaderItem(4).setText(QApplication.translate("Base", "Author", None))
        self.high_table.horizontalHeaderItem(5).setText(QApplication.translate("Base", "Page", None))
        self.high_table.horizontalHeaderItem(6).setText(QApplication.translate("Base", "Book path", None))
        self.act_english.setText(QApplication.translate("Base", "English", None))
        self.act_greek.setText(QApplication.translate("Base", "Greek", None))
        self.act_view_book.setText(QApplication.translate("Base", "View Book", None))
        self.act_view_book.setShortcut(QApplication.translate("Base", "Ctrl+B", None))

from secondary import DropTableWidget
import images_rc
